name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PYTHONPATH: /home/runner/work/BEKK/BEKK

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checking $(pwd)
      run: echo $(pwd)

    - name: Checking $PYTHONPATH
      run: echo $PYTHONPATH

    - name: Install dependencies (dev_env)
      run: make dev_env

    - name: Test (Lint Unit)
      run: make tests

    # DEFAULT ACTIONS FROM GITHUB ACTIONS

    # - name: configure
    #   run: ./configure

    # - name: Run check
    #   run: make check

    # - name: Run distcheck
    #   run: make distcheck
