name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PYTHONPATH: /home/runner/work/BEKK/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: configure
    #   run: ./configure

    - name: Install dependencies (dev_env)
      run: make dev_env

    # - name: Run check
    #   run: make check

    # - name: Run distcheck
    #   run: make distcheck

    - name: Test (Lint Unit)
      run: make tests
