name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PYTHONPATH: /home/runner/work/BEKK/BEKK

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: configure
    #   run: ./configure

    - name: Checking pwd
      run: echo $(pwd)

    # - name: Testing PATH
    #   run: echo "::set-env name=PYTHONPATH::home/runner/work/BEKK"

    - name: Set $PYTHONPATH
      run: export PYTHONPATH=$PYTHONPATH:$(pwd)

    - name: Install dependencies (dev_env)
      run: make dev_env

    - name: Checking $PYTHONPATH
      run: echo $PYTHONPATH

    # - name: Run check
    #   run: make check

    # - name: Run distcheck
    #   run: make distcheck

    - name: Test (Lint Unit)
      run: make tests
